# Use the official Python image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the models directory
COPY ./xspeciesApp/models /app/xspeciesApp/models

# Copy the entire project
COPY . /app/

# Create necessary directories
RUN mkdir -p /app/media/processed /app/media/temp && \
    mkdir -p /app/static

# Expose the port Django will run on
EXPOSE 8000

# Set the default command to run the development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
